# -*- coding: utf-8 -*-
"""Pull_From_BLS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rmVDmoJyPCdH4QT0JCk0zoTSpcj1DkFU
"""

pip install streamlit

import streamlit as st
import requests
import pandas as pd
import matplotlib.pyplot as plt

# Replace with your BLS API key
API_KEY = '22fddc1846284403b42a8a2326b03d8f'

# Function to fetch data from the BLS API
def fetch_bls_data(series_id):
    url = f'https://api.bls.gov/publicAPI/v2/timeseries/data/{series_id}?registrationKey={API_KEY}'
    response = requests.get(url)
    data = response.json()
    return data

# Function to extract data into a DataFrame
def extract_data(data):
    months = [entry['year'] + '-' + entry['period'][1:] for entry in data['Results']['series'][0]['data']]
    values = [entry['value'] for entry in data['Results']['series'][0]['data']]
    df = pd.DataFrame({
        'Month': months,
        'Value': values
    })
    df['Month'] = pd.to_datetime(df['Month'], format='%Y-%m')
    df['Value'] = pd.to_numeric(df['Value'], errors='coerce')
    return df

# Fetch data from BLS API
non_farm_workers_data = fetch_bls_data('CES0000000001')
unemployment_rate_data = fetch_bls_data('LNS14000000')

# Extract data into DataFrames
df_non_farm_workers = extract_data(non_farm_workers_data)
df_unemployment_rate = extract_data(unemployment_rate_data)

# Streamlit Dashboard
st.title("BLS Economic Data Dashboard")

# Display non-farm workers data
st.header("Total Non-Farm Workers (in thousands)")
st.write(df_non_farm_workers.tail())

# Plot non-farm workers
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(df_non_farm_workers['Month'], df_non_farm_workers['Value'], label='Non-Farm Workers', color='blue')
ax.set_title('Total Non-Farm Workers Over Time')
ax.set_xlabel('Month')
ax.set_ylabel('Non-Farm Workers (Thousands)')
plt.xticks(rotation=45)
st.pyplot(fig)

# Display unemployment rate data
st.header("Unemployment Rate (%)")
st.write(df_unemployment_rate.tail())

# Plot unemployment rate
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(df_unemployment_rate['Month'], df_unemployment_rate['Value'], label='Unemployment Rate', color='red')
ax.set_title('Unemployment Rate Over Time')
ax.set_xlabel('Month')
ax.set_ylabel('Unemployment Rate (%)')
plt.xticks(rotation=45)
st.pyplot(fig)

# Optionally: Additional Series (Labor Force Participation Rate, Employment-Population Ratio, etc.)
additional_series = ['LNS11300000', 'LNS12300000']  # Add more series as needed
for series_id in additional_series:
    st.subheader(f"Data for {series_id}")
    data = fetch_bls_data(series_id)
    df_additional = extract_data(data)
    st.write(df_additional.tail())

    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(df_additional['Month'], df_additional['Value'], label=series_id)
    ax.set_title(f'{series_id} Over Time')
    ax.set_xlabel('Month')
    ax.set_ylabel('Value')
    plt.xticks(rotation=45)
    st.pyplot(fig)